-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I ,REST_REVIEW R
--서울 위치
WHERE I.REST_ID = R.REST_ID
AND I.ADDRESS LIKE '서울%' 

GROUP BY I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS

--평균점수 내림차순
--즐겨찾기 순 내림차순
ORDER BY SCORE DESC, I.FAVORITES DESC;