-- 코드를 입력하세요
SELECT GB.TITLE, GB.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS,
TO_CHAR(GR.CREATED_DATE,'YYYY-MM-DD') CREATE_DATE
FROM USED_GOODS_BOARD GB, USED_GOODS_REPLY GR
WHERE GB.BOARD_ID = GR.BOARD_ID
AND EXTRACT(YEAR FROM GB.CREATED_DATE) = 2022
AND EXTRACT(MONTH FROM GB.CREATED_DATE) = 10

-- 정렬
ORDER BY GR.CREATED_DATE, GB.TITLE;